# Generated by Django 5.2 on 2025-04-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='github_avatar_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
