# Generated by Django 5.2 on 2025-05-02 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_githubtoken_token_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            "DROP TABLE IF EXISTS integrations_providerassociation;",
            state_operations=[]
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS integrations_gradelink;", 
            state_operations=[]
        ),
    ]
