# Generated by Django 5.2 on 2025-04-29 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_githubtoken_team_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Repository',
        ),
    ]
