# Generated by Django 5.2.1 on 2025-05-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile_timezone'),
        ('lms', '0004_canvasquiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='canvas_group_set_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='Canvas group category/set ID', null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='canvas_group_set_name',
            field=models.CharField(blank=True, help_text='Canvas group category/set name', max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['canvas_group_set_id'], name='core_team_canvas__89b21e_idx'),
        ),
    ]
