# Generated by Django 5.2 on 2025-04-30 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_repository'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professorprofile',
            options={},
        ),
        migrations.AlterModelOptions(
            name='studentprofile',
            options={},
        ),
        migrations.AlterModelOptions(
            name='taprofile',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
    ]
