# Generated by Django 5.2.1 on 2025-05-15 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_team_canvas_group_set_id_team_canvas_group_set_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='taiga_project',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
