# Generated by Django 5.2.1 on 2025-05-16 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_team_github_repo_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='github_repo_name',
        ),
    ]
