# Generated by Django 5.2 on 2025-05-01 01:06

from django.db import migrations


def migrate_students(apps, schema_editor):
    """
    Migrate existing StudentProfile records to the new Student model
    """
    # Get the models from the migration state
    StudentProfile = apps.get_model('core', 'StudentProfile')
    Student = apps.get_model('core', 'Student')
    
    # Migrate each StudentProfile to a Student record
    for student_profile in StudentProfile.objects.all():
        # Get user info
        try:
            user = student_profile.user_profile.user
            
            # Create new Student record with data from the StudentProfile
            student = Student.objects.create(
                first_name=user.first_name,
                last_name=user.last_name,
                email=user.email,
                student_id=student_profile.student_id,
                team=student_profile.team,
                github_username=student_profile.github_username or student_profile.user_profile.github_username,
                taiga_username=student_profile.taiga_username,
                created_by=user
            )
            
            print(f"Migrated student profile for {user.username} to new Student model: {student}")
        except Exception as e:
            print(f"Error migrating student profile: {e}")


def reverse_migration(apps, schema_editor):
    """
    Reverse migration - remove all Student records
    """
    Student = apps.get_model('core', 'Student')
    Student.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_studentprofile_user_profile_student'),
    ]

    operations = [
        migrations.RunPython(
            migrate_students,
            reverse_migration
        ),
    ]
