# Generated by Django 5.2.1 on 2025-05-16 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_team_github_repo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='github_repo_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
