# Generated by Django 5.2.1 on 2025-05-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_student_avatar_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Team', 'verbose_name_plural': 'Teams'},
        ),
        migrations.AlterField(
            model_name='team',
            name='canvas_group_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='Canvas group ID (from /api/v1/groups/:id).', null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='canvas_group_set_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='Canvas group set (category) ID.', null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='canvas_group_set_name',
            field=models.CharField(blank=True, help_text='Canvas group set (category) name.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when this Team record was created.'),
        ),
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.TextField(blank=True, help_text='Optional detailed description of the team.', null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='github_organization',
            field=models.CharField(blank=True, help_text='GitHub organization name for this team.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='github_repo_name',
            field=models.CharField(blank=True, help_text='GitHub repository name under the organization.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='github_team_id',
            field=models.CharField(blank=True, help_text='GitHub API team ID (numeric string).', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when this team was last synced with Canvas.', null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(help_text='Human-readable team name.', max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='taiga_project',
            field=models.CharField(blank=True, help_text='Taiga project slug or name.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='taiga_project_id',
            field=models.CharField(blank=True, help_text='Taiga API project ID (numeric string).', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when this Team record was last updated.'),
        ),
    ]
