# Generated by Django 5.2.1 on 2025-05-17 12:40

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_professorprofile_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubtoken',
            name='token',
            field=encrypted_model_fields.fields.EncryptedCharField(help_text='Encrypted GitHub API token'),
        ),
        migrations.AlterField(
            model_name='professorprofile',
            name='lms_access_token',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='Encrypted Learning Management System (LMS) API access token', null=True),
        ),
        migrations.AlterField(
            model_name='professorprofile',
            name='lms_refresh_token',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='Encrypted LMS API refresh token for obtaining new access tokens', null=True),
        ),
        migrations.AlterField(
            model_name='taprofile',
            name='lms_access_token',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='Encrypted Learning Management System (LMS) API access token', null=True),
        ),
        migrations.AlterField(
            model_name='taprofile',
            name='lms_refresh_token',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='Encrypted LMS API refresh token for obtaining new access tokens', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='github_access_token',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='Encrypted GitHub personal access token for API authentication', null=True),
        ),
    ]
