# Generated by Django 5.2 on 2025-05-01 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_migrate_student_profiles'),
        ('project_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='member',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='member',
            name='student_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taiga_member', to='core.studentprofile'),
        ),
        migrations.AlterField(
            model_name='member',
            name='student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taiga_member', to='core.student'),
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('student_profile', 'project')},
        ),
    ]
