# Generated by Django 5.2.1 on 2025-05-17 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_student_avatar_url'),
        ('project_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'Taiga Member', 'verbose_name_plural': 'Taiga Members'},
        ),
        migrations.AlterField(
            model_name='member',
            name='color',
            field=models.CharField(help_text="Hex color code associated with this role (e.g., '#ff0000').", max_length=7),
        ),
        migrations.AlterField(
            model_name='member',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when this Member record was created.'),
        ),
        migrations.AlterField(
            model_name='member',
            name='project',
            field=models.ForeignKey(help_text='The Taiga project this member belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='project_mgmt.project'),
        ),
        migrations.AlterField(
            model_name='member',
            name='role_name',
            field=models.CharField(help_text='Role of the member in the project (e.g., Developer, Manager).', max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='student',
            field=models.OneToOneField(help_text='The Student associated with this Taiga member.', on_delete=django.db.models.deletion.CASCADE, related_name='taiga_member', to='core.student'),
        ),
        migrations.AlterField(
            model_name='member',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when this Member record was last updated.'),
        ),
    ]
