# Generated by Django 5.2 on 2025-05-01 13:28

import core.async_utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rubric_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('points_possible', models.DecimalField(decimal_places=2, max_digits=8)),
                ('reusable', models.BooleanField(default=False)),
                ('read_only', models.BooleanField(default=False)),
                ('free_form_criterion_comments', models.BooleanField(default=True)),
                ('hide_score_total', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            bases=(models.Model, core.async_utils.AsyncModelMixin),
        ),
        migrations.CreateModel(
            name='CanvasCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('course_code', models.CharField(blank=True, max_length=100)),
                ('term', models.CharField(blank=True, max_length=100)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canvas_courses', to='core.team')),
            ],
            bases=(models.Model, core.async_utils.AsyncModelMixin),
        ),
        migrations.CreateModel(
            name='CanvasAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('grading_type', models.CharField(default='points', max_length=20)),
                ('rubric_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='lms.canvascourse')),
            ],
            bases=(models.Model, core.async_utils.AsyncModelMixin),
        ),
        migrations.CreateModel(
            name='Canvas',
            fields=[
            ],
            options={
                'verbose_name': 'Canvas',
                'verbose_name_plural': 'Canvas',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('lms.canvascourse',),
        ),
        migrations.CreateModel(
            name='RubricAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_for_grading', models.BooleanField(default=True)),
                ('purpose', models.CharField(default='grading', max_length=50)),
                ('hide_score_total', models.BooleanField(default=False)),
                ('hide_points', models.BooleanField(default=False)),
                ('hide_outcome_results', models.BooleanField(default=False)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rubric_associations', to='lms.canvasassignment')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rubric_associations', to='lms.canvascourse')),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associations', to='lms.rubric')),
            ],
            options={
                'unique_together': {('rubric', 'course', 'assignment')},
            },
            bases=(models.Model, core.async_utils.AsyncModelMixin),
        ),
        migrations.CreateModel(
            name='RubricCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterion_id', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('long_description', models.TextField(blank=True, null=True)),
                ('points', models.DecimalField(decimal_places=2, max_digits=8)),
                ('criterion_use_range', models.BooleanField(default=False)),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='lms.rubric')),
            ],
            bases=(models.Model, core.async_utils.AsyncModelMixin),
        ),
        migrations.CreateModel(
            name='RubricRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_id', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('long_description', models.TextField(blank=True, null=True)),
                ('points', models.DecimalField(decimal_places=2, max_digits=8)),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='lms.rubriccriterion')),
            ],
            bases=(models.Model, core.async_utils.AsyncModelMixin),
        ),
        migrations.CreateModel(
            name='CanvasEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_id', models.IntegerField(unique=True)),
                ('role', models.CharField(max_length=30)),
                ('course_section_id', models.IntegerField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='lms.canvascourse')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canvas_enrollments', to='core.student')),
            ],
            options={
                'unique_together': {('course', 'student')},
            },
            bases=(models.Model, core.async_utils.AsyncModelMixin),
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='lms.canvasassignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='core.student')),
            ],
            options={
                'unique_together': {('student', 'assignment')},
            },
            bases=(models.Model, core.async_utils.AsyncModelMixin),
        ),
        migrations.CreateModel(
            name='RubricAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_type', models.CharField(default='Submission', max_length=50)),
                ('artifact_id', models.IntegerField()),
                ('artifact_attempt', models.IntegerField(default=1)),
                ('assessment_type', models.CharField(default='grading', max_length=50)),
                ('score', models.DecimalField(decimal_places=2, max_digits=8)),
                ('data', models.JSONField()),
                ('comments', models.JSONField()),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rubric_assessments', to='core.userprofile')),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='lms.rubric')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubric_assessments', to='core.student')),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='lms.rubricassociation')),
            ],
            options={
                'unique_together': {('association', 'student', 'assessor')},
            },
            bases=(models.Model, core.async_utils.AsyncModelMixin),
        ),
    ]
