# Generated by Django 5.2.1 on 2025-05-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0001_initial"),
    ]

    operations = [
        # Rename last_synced_at field to updated_at in CanvasGroupCategory
        migrations.RenameField(
            model_name="canvasgroupcategory",
            old_name="last_synced_at",
            new_name="updated_at",
        ),
        # Rename last_synced_at field to updated_at in CanvasGroup
        migrations.RenameField(
            model_name="canvasgroup",
            old_name="last_synced_at",
            new_name="updated_at",
        ),
    ]
