# Generated by Django 5.2 on 2025-05-01 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_migrate_student_profiles'),
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='canvasenrollment',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='rubricassessment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='canvasenrollment',
            name='student_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='canvas_enrollments_legacy', to='core.studentprofile'),
        ),
        migrations.AddField(
            model_name='rubricassessment',
            name='student_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rubric_assessments_legacy', to='core.studentprofile'),
        ),
        migrations.AlterField(
            model_name='canvasenrollment',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='canvas_enrollments', to='core.student'),
        ),
        migrations.AlterField(
            model_name='rubricassessment',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rubric_assessments', to='core.student'),
        ),
        migrations.AlterUniqueTogether(
            name='canvasenrollment',
            unique_together={('course', 'student_profile')},
        ),
        migrations.AlterUniqueTogether(
            name='rubricassessment',
            unique_together={('association', 'student_profile', 'assessor')},
        ),
    ]
