# Generated by Django 5.2 on 2025-05-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_calendarevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendarevent',
            options={'ordering': ('start',)},
        ),
        migrations.RenameField(
            model_name='calendarevent',
            old_name='end_at',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='calendarevent',
            old_name='created_at_canvas',
            new_name='start',
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='event_id',
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='start_at',
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='updated_at_canvas',
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='raw_ics',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='rrule',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='uid',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
