# Generated by Django 5.2.1 on 2025-05-11 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0002_update_group_timestamp_fields"),
    ]

    operations = [
        migrations.RenameField(
            model_name="canvasgroup",
            old_name="updated_at",
            new_name="last_synced_at",
        ),
        migrations.RenameField(
            model_name="canvasgroupcategory",
            old_name="updated_at",
            new_name="last_synced_at",
        ),
    ]
