# Generated by Django 5.2.1 on 2025-05-13 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0003_rename_updated_at_canvasgroup_last_synced_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CanvasQuiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("canvas_id", models.PositiveIntegerField(unique=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "quiz_type",
                    models.CharField(
                        choices=[
                            ("assignment", "Assignment"),
                            ("practice_quiz", "Practice Quiz"),
                            ("graded_survey", "Graded Survey"),
                            ("survey", "Survey"),
                        ],
                        default="assignment",
                        max_length=20,
                    ),
                ),
                ("time_limit", models.PositiveIntegerField(blank=True, null=True)),
                ("shuffle_answers", models.BooleanField(default=False)),
                ("one_question_at_a_time", models.BooleanField(default=False)),
                ("show_correct_answers", models.BooleanField(default=True)),
                (
                    "hide_results",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("lock_at", models.DateTimeField(blank=True, null=True)),
                ("unlock_at", models.DateTimeField(blank=True, null=True)),
                ("points_possible", models.FloatField(default=0.0)),
                (
                    "scoring_policy",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("published", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assignment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz",
                        to="lms.canvasassignment",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quizzes",
                        to="lms.canvascourse",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Canvas Quizzes",
                "ordering": ["-created_at"],
            },
        ),
    ]
