# Generated by Django 5.2.1 on 2025-05-16 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_canvasquiz'),
    ]

    operations = [
        # First fix any invalid student references
        migrations.RunSQL(
            "UPDATE lms_canvasgroupmembership SET student_id = NULL WHERE student_id NOT IN (SELECT id FROM core_student)",
            reverse_sql=migrations.RunSQL.noop
        ),
        # Then add the is_leader field
        migrations.AddField(
            model_name='canvasgroupmembership',
            name='is_leader',
            field=models.BooleanField(default=False),
        ),
    ]
