# Generated by Django 5.2.1 on 2025-05-16 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_canvasgroupmembership_is_leader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canvasgroupmembership',
            name='is_leader',
        ),
    ]
