# Generated by Django 5.2.1 on 2025-05-17 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_remove_canvasgroupmembership_is_leader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canvasintegration',
            name='last_sync',
        ),
        migrations.AddField(
            model_name='canvasgroup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='canvasgroupcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='canvasintegration',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='canvasgroup',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='canvasgroupcategory',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
