# Generated by Django 5.2.1 on 2025-05-17 12:40

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0007_remove_canvasintegration_last_sync_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canvasintegration',
            name='api_key',
            field=encrypted_model_fields.fields.EncryptedCharField(help_text='Encrypted Canvas API key for authentication'),
        ),
        migrations.AlterField(
            model_name='canvasintegration',
            name='refresh_token',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='Encrypted Canvas OAuth2 refresh token', null=True),
        ),
    ]
