# Generated by Django 5.2.1 on 2025-05-17 13:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0008_alter_canvasintegration_api_key_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='canvasgroupmembership',
            old_name='added_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='canvasgroup',
            name='canvas_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='canvasgroupcategory',
            name='canvas_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='canvasgroupmembership',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='canvasgroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='canvasgroupcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
