# Generated by Django 5.2.1 on 2025-05-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0009_rename_added_at_canvasgroupmembership_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canvasassignment',
            name='canvas_id',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
