# Generated by Django 5.2 on 2025-05-01 00:43

import core.async_utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lms_course_id', models.CharField(max_length=100)),
                ('lms_assignment_id', models.CharField(max_length=100)),
                ('git_repository_id', models.CharField(max_length=100)),
                ('project_task_id', models.CharField(blank=True, max_length=100, null=True)),
                ('student_id', models.CharField(max_length=100)),
                ('grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('graded_by', models.CharField(blank=True, max_length=100)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Grade Link',
                'verbose_name_plural': 'Grade Links',
            },
            bases=(models.Model, core.async_utils.AsyncModelMixin),
        ),
        migrations.CreateModel(
            name='ProviderAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_object_id', models.PositiveIntegerField()),
                ('target_object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('association_type', models.CharField(max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('source_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_associations', to='contenttypes.contenttype')),
                ('target_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_associations', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Provider Association',
                'verbose_name_plural': 'Provider Associations',
                'indexes': [models.Index(fields=['source_content_type', 'source_object_id'], name='integration_source__b5ce28_idx'), models.Index(fields=['target_content_type', 'target_object_id'], name='integration_target__31118b_idx')],
            },
            bases=(models.Model, core.async_utils.AsyncModelMixin),
        ),
    ]
