# Generated by Django 5.2 on 2025-05-01 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_migrate_student_profiles'),
        ('git_providers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborator',
            name='student_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='github_profile', to='core.studentprofile'),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='github_collaborator', to='core.student'),
        ),
    ]
