# Generated by Django 5.2.1 on 2025-05-14 13:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git_providers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commit',
            name='message',
        ),
        migrations.AddField(
            model_name='commit',
            name='author_email',
            field=models.EmailField(default='unknown@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='commit',
            name='author_name',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='commit',
            name='author_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='commit',
            name='committer_email',
            field=models.EmailField(default='unknown@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='commit',
            name='committer_name',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='commit',
            name='committer_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='commit',
            name='files_changed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commit',
            name='short_sha',
            field=models.CharField(blank=True, db_index=True, max_length=7),
        ),
        migrations.AddField(
            model_name='commit',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='CommitParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text="Order of this parent in the commit's parent list (for merge commits)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_relationships', to='git_providers.commit')),
                ('parent_commit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_relationships', to='git_providers.commit')),
            ],
            options={
                'ordering': ['commit', 'order'],
                'unique_together': {('commit', 'parent_commit')},
            },
        ),
    ]
