# Generated by Django 5.2.1 on 2025-05-17 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_student_avatar_url'),
        ('git_providers', '0002_remove_commit_message_commit_author_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when this Collaborator record was created.'),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='email',
            field=models.EmailField(blank=True, help_text='Public email address from GitHub profile (may be blank).', max_length=254),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='github_id',
            field=models.IntegerField(help_text='Numeric GitHub user ID, guaranteed unique.', unique=True),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='student',
            field=models.OneToOneField(help_text='The Student associated with this GitHub collaborator.', on_delete=django.db.models.deletion.CASCADE, related_name='github_collaborator', to='core.student'),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when this Collaborator record was last updated.'),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='username',
            field=models.CharField(help_text='GitHub login username.', max_length=255),
        ),
    ]
